### ISSUE TITLE
@hackbot's pug memes are out of date

### ISSUE THREAD

**Issue by andrewseward** [TechNottingham/hubot-hackbot#22]

**Comment by andrewseward** [comment]
https://github.com/hubot-scripts/hubot-pugme/issues/7

**Comment by nick599** [comment]
There seems to be a workaround on: https://github.com/hashashin/hubot-pugme/commit/2b2f8b97de56b797645a9c13b5fc5e91294ca7e6 . - Can someone with access alter the file  src/pugme.coffee ?

**Comment by andrewseward** [comment]
Fixed
