### ISSUE TITLE
Script to remove teams that have no members

### ISSUE THREAD

**Issue by nick599** [TechNottingham/hubot-hackbot#28]
Following the issue in https://github.com/TechNottingham/hubot-hackbot/issues/2 , it would be useful to have a command a hack24 staff / volunteer could run that removes team names that do not have currently any members for Hack24.

**Comment by Codesleuth** [comment]
Hackbot now checks if a team is empty when the last person leaves. I'm hoping it's enough to keep the list pruned, but there's a small possibility of race conditions.

**Comment by nick599** [comment]
Ok, there could be a few teams from previous Hack24's though with 0 members?

**Comment by andrewseward** [comment]
No, we cleared out last year's data
