### ISSUE TITLE
@hackbot kick @username from my team

### ISSUE THREAD

**Issue by Codesleuth** [TechNottingham/hubot-hackbot#3]
Remove the user specified by `@username` from the user's team. The API supports deleting team members with the following sample request:

``` http
DELETE /team/some-team-name/members HTTP/1.1
Content-Type: application/vnd.api+json

{
  "data": [{
    "type": "users",
    "id": "slackusername"
  }]
}
```

Successful requests respond with:

``` http
HTTP/1.1 204 No Content
```

Failed requests respond with:

``` http
HTTP/1.1 400 Bad Request
Content-Type: application/vnd.api+json

{
  "errors": [{
    "status": "400",
    "title": "Bad request."
  }]
}
```

Only attendees authenticating with the hackbot password (`HACKBOT_API_PASSWORD` env. variable) can kick a user from a team. Ideally, only users _within_ the team should be able to make this request, but this is not a problem since this is implied from the request itself.

**Comment by nick599** [comment]
Can this be closed now? - https://github.com/TechNottingham/hubot-hackbot/issues/30
