### ISSUE TITLE
Hackbot can be added to a team

### ISSUE THREAD

**Issue by andrewseward** [TechNottingham/hubot-hackbot#9]

**Comment by Codesleuth** [comment]
The command `add @hackbot to my team` (where `@hackbot` is a bot) should produce a warning and refuse to add the bot to the team. Only non-bots should be allowed to join a team.

To determine if a user is a bot, the [`@slack/client`](https://github.com/slackhq/node-slack-sdk) client provides a [`MemoryDataStore`](https://github.com/slackhq/node-slack-sdk/blob/master/lib/data-store/memory-data-store.js#L18) which can be accessed from the adapter:

``` ts
import { Robot } from 'hubot-slack';

// use `robot: Robot` to attach the client to the adapter type

const dataStore = robot.adapter.client.rtm.dataStore;
const isBot = dataStore.getUserByName(userName).is_bot;
```

A meaningful error should be reported to the user. You can even _be creative_ 😸
